#!/usr/bin/env bash
# Generated by scripts/Im_sorry_pod_setup.sh.
export WORKSPACE="/home/frosty40/SOTA_FINAL"
export PATH="/venv/main/bin:$PATH"
export DATA_PATH="./data/datasets/fineweb10B_sp8192"
export TOKENIZER_PATH="./data/tokenizers/fineweb_8192_bpe.model"
export VOCAB_SIZE="8192"
export TRAIN_SHARDS="80"
