#!/usr/bin/env bash
set -euo pipefail
export PIP_ROOT_USER_ACTION=ignore

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# Fail closed if protected pod setup files drifted.
bash "${REPO_ROOT}/scripts/pod_stack_guard.sh" verify

POD_VARIANT="${POD_VARIANT:-sp8192}"
TRAIN_SHARDS="${TRAIN_SHARDS:-80}"
DOWNLOAD_SP1024="${DOWNLOAD_SP1024:-1}"
DOWNLOAD_SP8192="${DOWNLOAD_SP8192:-1}"
REQUIRE_FA3="${REQUIRE_FA3:-1}"
REQUIRE_BROTLI="${REQUIRE_BROTLI:-1}"
REQUIRE_PYMINIFIER="${REQUIRE_PYMINIFIER:-1}"
REQUIRE_SP1024="${REQUIRE_SP1024:-1}"
REQUIRE_SP8192="${REQUIRE_SP8192:-1}"
BLOCK_CU124="${BLOCK_CU124:-1}"
export POD_VARIANT TRAIN_SHARDS DOWNLOAD_SP1024 DOWNLOAD_SP8192
export REQUIRE_FA3 REQUIRE_BROTLI REQUIRE_PYMINIFIER REQUIRE_SP1024 REQUIRE_SP8192 BLOCK_CU124

if [[ -n "${WORKSPACE:-}" ]]; then
    WORKSPACE="$(cd -- "${WORKSPACE}" && pwd)"
else
    WORKSPACE="${REPO_ROOT}"
fi
export WORKSPACE

DATA_HELPER="${WORKSPACE}/data/cached_challenge_fineweb.py"
FA3_SRC="${WORKSPACE}/flash-attention/hopper/flash_attn_interface.py"
ACTIVATE_HELPER="${WORKSPACE}/scripts/activate_pod_env.sh"
SP8192_REPO_PRIMARY="${MATCHED_FINEWEB_REPO_ID:-kevclark/parameter-golf}"
SP8192_REPO_FALLBACK="${MATCHED_FINEWEB_REPO_FALLBACK:-willdepueoai/parameter-golf}"
SP1024_REPO_PRIMARY="${MATCHED_FINEWEB_REPO_ID_1024:-willdepueoai/parameter-golf}"
SP1024_REPO_FALLBACK="${MATCHED_FINEWEB_REPO_FALLBACK_1024:-kevclark/parameter-golf}"

write_activation_helper() {
    local vocab_size="${POD_VARIANT#sp}"
    [[ "${vocab_size}" =~ ^[0-9]+$ ]] || vocab_size="8192"
    mkdir -p "${WORKSPACE}/scripts"
    cat > "${ACTIVATE_HELPER}" <<EOF_HELPER
#!/usr/bin/env bash
# Generated by scripts/Im_sorry_pod_setup.sh.
export WORKSPACE="${WORKSPACE}"
export PATH="/venv/main/bin:\$PATH"
export DATA_PATH="./data/datasets/fineweb10B_${POD_VARIANT}"
export TOKENIZER_PATH="./data/tokenizers/fineweb_${POD_VARIANT#sp}_bpe.model"
export VOCAB_SIZE="${vocab_size}"
export TRAIN_SHARDS="${TRAIN_SHARDS}"
EOF_HELPER
    chmod +x "${ACTIVATE_HELPER}"
    echo "  Wrote scripts/activate_pod_env.sh"
}

install_fa3() {
    echo "  Attempting FA3 abi3 wheel (cu128)..."
    if pip install --no-cache-dir \
        "https://download.pytorch.org/whl/cu128/flash_attn_3-3.0.0-cp39-abi3-manylinux_2_28_x86_64.whl" \
        2>&1 | tail -3; then
        return 0
    fi

    echo "  Wheels failed. Checking for local flash-attention/hopper source..."
    if [[ -f "${FA3_SRC}" ]]; then
        SITE="$(python3 -c "import site; print(site.getsitepackages()[0])")"
        ln -sf "${FA3_SRC}" "${SITE}/flash_attn_interface.py"
        echo "  Symlinked flash_attn_interface.py into site-packages"
        return 0
    fi

    echo "  FATAL: Could not install FA3 hopper. SDPA fallback is disabled."
    return 1
}

download_variant() {
    local variant="$1"
    shift
    local repo_id

    for repo_id in "$@"; do
        [[ -n "${repo_id}" ]] || continue
        rm -f data/manifest.json
        if MATCHED_FINEWEB_REPO_ID="${repo_id}" \
            python3 data/cached_challenge_fineweb.py --variant "${variant}" --train-shards "${TRAIN_SHARDS}"; then
            rm -f data/manifest.json
            return 0
        fi
        echo "  WARNING: ${variant} download failed from ${repo_id}"
    done

    rm -f data/manifest.json
    return 1
}

verify_core_stack() {
    python3 - <<'PYEOF'
import torch
print("VERIFY_OK")
print(f"torch={torch.__version__} cuda={torch.version.cuda}")
print(f"gpus={torch.cuda.device_count()}")
print("data_checks=skipped")
PYEOF
}

verify_ready_stack() {
    python3 - <<'PYEOF'
import glob
import os
import torch

root = os.environ.get("WORKSPACE", os.getcwd())
variant = os.environ.get("POD_VARIANT", "sp8192")
expected_train = int(os.environ.get("TRAIN_SHARDS", "80"))
expected_val = 1
label = variant.upper()
require_fa3 = os.environ.get("REQUIRE_FA3", "1") == "1"
require_brotli = os.environ.get("REQUIRE_BROTLI", "1") == "1"
require_pyminifier = os.environ.get("REQUIRE_PYMINIFIER", "1") == "1"
require_sp1024 = os.environ.get("REQUIRE_SP1024", "1") == "1"
require_sp8192 = os.environ.get("REQUIRE_SP8192", "1") == "1"
block_cu124 = os.environ.get("BLOCK_CU124", "1") == "1"

def path_join(*parts: str) -> str:
    return os.path.join(*parts)

fa_ok = False
try:
    import flash_attn_interface
    fa_path = getattr(flash_attn_interface, "__file__", "MISSING")
    fa_ok = True
except Exception:
    fa_path = "MISSING"

pm_ok = False
try:
    import python_minifier
    pm_path = getattr(python_minifier, "__file__", "MISSING")
    pm_ver = getattr(python_minifier, "__version__", "unknown")
    pm_ok = True
except Exception:
    pm_path = "MISSING"
    pm_ver = "unknown"

brotli_ok = False
try:
    import brotli
    brotli_path = getattr(brotli, "__file__", "MISSING")
    brotli_ver = getattr(brotli, "__version__", "unknown")
    brotli_ok = True
except Exception:
    brotli_path = "MISSING"
    brotli_ver = "unknown"

train_dir = path_join(root, "data", "datasets", f"fineweb10B_{variant}")
train = sorted(glob.glob(path_join(train_dir, "fineweb_train_*.bin")))
val = sorted(glob.glob(path_join(train_dir, "fineweb_val_*.bin")))
sp8192_tok = path_join(root, "data", "tokenizers", "fineweb_8192_bpe.model")
sp1024_tok = path_join(root, "data", "tokenizers", "fineweb_1024_bpe.model")
sp8192_train = sorted(glob.glob(path_join(root, "data", "datasets", "fineweb10B_sp8192", "fineweb_train_*.bin")))
sp8192_val = sorted(glob.glob(path_join(root, "data", "datasets", "fineweb10B_sp8192", "fineweb_val_*.bin")))
sp1024_train = sorted(glob.glob(path_join(root, "data", "datasets", "fineweb10B_sp1024", "fineweb_train_*.bin")))
sp1024_val = sorted(glob.glob(path_join(root, "data", "datasets", "fineweb10B_sp1024", "fineweb_val_*.bin")))

torch_stack = f"{torch.__version__}+cuda{torch.version.cuda}"

print(f"FA3_OK_PATH:{fa_path}")
print(f"TORCH_STACK:{torch_stack}")
print(f"PYMINIFIER_PATH:{pm_path}")
print(f"PYMINIFIER_VER:{pm_ver}")
print(f"BROTLI_PATH:{brotli_path}")
print(f"BROTLI_VER:{brotli_ver}")
print(f"{label}_TRAIN_SHARDS:{len(train)}")
print(f"{label}_VAL_SHARDS:{len(val)}")
print(f"SP8192_TOKENIZER:{sp8192_tok} exists={os.path.isfile(sp8192_tok)}")
print(f"SP1024_TOKENIZER:{sp1024_tok} exists={os.path.isfile(sp1024_tok)}")
print(f"SP8192_SHARDS train={len(sp8192_train)} val={len(sp8192_val)}")
print(f"SP1024_SHARDS train={len(sp1024_train)} val={len(sp1024_val)}")
print("VERIFY_OK")
print(f"torch={torch.__version__} cuda={torch.version.cuda}")
print(f"gpus={torch.cuda.device_count()}")
print(f"dataset=fineweb10B_{variant} train_shards={len(train)} val_shards={len(val)}")

if block_cu124 and ("cu124" in torch.__version__ or str(torch.version.cuda).startswith("12.4")):
    raise SystemExit(f"FATAL: cu124 stack detected in torch/cuda ({torch_stack})")

if require_fa3 and not fa_ok:
    raise SystemExit("FATAL: FA3 is required but flash_attn_interface import failed")

if require_brotli and not brotli_ok:
    raise SystemExit("FATAL: brotli is required but import failed")

if require_pyminifier and not pm_ok:
    raise SystemExit("FATAL: python_minifier is required but import failed")

if require_sp8192:
    if not os.path.isfile(sp8192_tok):
        raise SystemExit("FATAL: required tokenizer missing: fineweb_8192_bpe.model")
    if len(sp8192_train) != expected_train or len(sp8192_val) != expected_val:
        raise SystemExit(
            f"FATAL: required SP8192 dataset incomplete: train={len(sp8192_train)} val={len(sp8192_val)} expected={expected_train}/{expected_val}"
        )

if require_sp1024:
    if not os.path.isfile(sp1024_tok):
        raise SystemExit("FATAL: required tokenizer missing: fineweb_1024_bpe.model")
    if len(sp1024_train) != expected_train or len(sp1024_val) != expected_val:
        raise SystemExit(
            f"FATAL: required SP1024 dataset incomplete: train={len(sp1024_train)} val={len(sp1024_val)} expected={expected_train}/{expected_val}"
        )
PYEOF
}

echo "============================================"
echo "  POD SETUP"
echo "  Workspace: ${WORKSPACE}"
echo "  Variant: ${POD_VARIANT}"
echo "  Train shards: ${TRAIN_SHARDS}"
echo "  Repo sync: DISABLED"
echo "============================================"

echo ""
echo ""
echo "[1/5] Checking base environment..."

python3 --version || { echo "FATAL: python3 not found"; exit 1; }
python3 -c "import torch; print(f'  PyTorch {torch.__version__}  CUDA {torch.version.cuda}')" \
    || { echo "FATAL: PyTorch not installed in active python3"; exit 1; }

TORCH_LIB="$(python3 - <<'PYEOF'
import os
import torch
print(os.path.join(os.path.dirname(torch.__file__), "lib"))
PYEOF
)"
export LD_LIBRARY_PATH="${TORCH_LIB}:${LD_LIBRARY_PATH:-}"

GPU_COUNT="$(python3 -c "import torch; print(torch.cuda.device_count())" 2>/dev/null || echo "0")"
if [[ "${GPU_COUNT}" -eq 0 ]]; then
    echo "  WARNING: No GPUs detected"
else
    python3 - <<'PYEOF' 2>/dev/null || true
import torch
for i in range(torch.cuda.device_count()):
    p = torch.cuda.get_device_properties(i)
    print(f"  GPU {i}: {p.name} ({p.total_memory // 1024**3}GB)")
PYEOF
fi

if [[ -d /workspace/venv_cu124 ]]; then
    echo "  NOTE: ignoring stale /workspace/venv_cu124; setup uses the pod's active python3"
fi

write_activation_helper

echo ""
echo "[2/5] Installing pip packages..."

pip install --upgrade pip -q 2>&1 | tail -1

pip install numpy tqdm huggingface-hub kernels setuptools \
    "typing-extensions==4.15.0" datasets tiktoken sentencepiece attr python-minifier -q 2>&1 | tail -1
echo "  Core packages OK"

echo ""
echo "[3/5] zstandard + brotli..."

if python3 -c "import zstandard" 2>/dev/null; then
    echo "  zstandard: already installed"
else
    pip install zstandard -q
    echo "  zstandard: installed"
fi
python3 -c "import zstandard; print(f'  zstandard {zstandard.__version__}')"

if python3 -c "import brotli" 2>/dev/null; then
    echo "  brotli: already installed"
else
    pip install brotli -q
    echo "  brotli: installed"
fi
python3 -c "import brotli; print(f'  brotli {brotli.__version__}')" 2>/dev/null || echo "  brotli OK"

echo ""
echo "[4/5] FlashAttention-3..."

if python3 -c "from flash_attn_interface import flash_attn_func; print('  FA3 (flash_attn_interface) OK')" 2>/dev/null; then
    :
elif python3 -c "import flash_attn; v=flash_attn.__version__; assert v.startswith('3'); print(f'  FA3 v{v} OK')" 2>/dev/null; then
    :
else
    install_fa3
fi

verify_core_stack

echo ""
echo "[5/5] Tokenizer + FineWeb dataset (${POD_VARIANT})..."

if [[ ! -f "${DATA_HELPER}" ]]; then
    echo "  WARNING: data helper not found at ${DATA_HELPER}"
    echo "  Skipping dataset download. Run this script from a project root that has data/cached_challenge_fineweb.py"
else
    cd "${WORKSPACE}"

    if [[ "${POD_VARIANT}" == "sp8192" ]]; then
        if [[ "${DOWNLOAD_SP8192}" == "1" ]]; then
            echo "  Using competition download script (data/cached_challenge_fineweb.py)..."
            download_variant "sp8192" "${SP8192_REPO_PRIMARY}" "${SP8192_REPO_FALLBACK}" || {
                echo "  WARNING: SP8192 download failed"
            }
        else
            echo "  Skipping SP8192 download (DOWNLOAD_SP8192=${DOWNLOAD_SP8192})"
        fi
    fi

    if [[ "${DOWNLOAD_SP1024}" == "1" ]]; then
        echo "  Downloading SP1024..."
        download_variant "sp1024" "${SP1024_REPO_PRIMARY}" "${SP1024_REPO_FALLBACK}" || {
            echo "  WARNING: SP1024 download failed"
        }
    fi
fi

echo ""
echo "============================================"
echo " Verification"
echo "============================================"

python3 -m pip show flash_attn_3 2>/dev/null || true
verify_ready_stack

echo ""
echo "============================================"
echo " READY."
echo "============================================"
